/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package com.desgroup.eventlogistics;

import com.desgroup.models.Logistic;
import com.desgroup.models.Coordinator;
import com.desgroup.ui.LoginFrame2;
import com.desgroup.ui.LogisticOpcion;
import java.awt.EventQueue;
import javax.swing.UIManager;
import com.desgroup.models.Staff;

/**
 *
 * @author urreg
 */
public class Main extends javax.swing.JFrame {
    private LogisticOpcion frame;
    private Staff CurrentUser;
    /**
     * Creates new form Main
     */
    public Main(Staff CurrentUser) {
        this.CurrentUser = CurrentUser;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuEventLogistic = new javax.swing.JMenuBar();
        mnuLogistic = new javax.swing.JMenu();
        mniShowUser = new javax.swing.JMenuItem();
        mnuCoordinator = new javax.swing.JMenu();
        mniManageLogistic = new javax.swing.JMenuItem();
        mniShowAssignmentsCoor = new javax.swing.JMenuItem();
        mniShowSalaryCoor = new javax.swing.JMenuItem();
        mnuManager = new javax.swing.JMenu();
        mniManageEvents = new javax.swing.JMenuItem();
        mniManageCoordinators = new javax.swing.JMenuItem();
        mnuOptions = new javax.swing.JMenu();
        mniLogOut = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mnuLogistic.setMnemonic('e');
        mnuLogistic.setText("Logistico");

        mniShowUser.setMnemonic('p');
        mniShowUser.setText("Ver perfil");
        mniShowUser.addActionListener(this::mniShowUserActionPerformed);
        mnuLogistic.add(mniShowUser);

        menuEventLogistic.add(mnuLogistic);

        mnuCoordinator.setMnemonic('h');
        mnuCoordinator.setText("Cordinador");

        mniManageLogistic.setMnemonic('c');
        mniManageLogistic.setText("Administrar logisticos");
        mnuCoordinator.add(mniManageLogistic);

        mniShowAssignmentsCoor.setMnemonic('a');
        mniShowAssignmentsCoor.setText("Ver eventos asignados");
        mniShowAssignmentsCoor.addActionListener(this::mniShowAssignmentsCoorActionPerformed);
        mnuCoordinator.add(mniShowAssignmentsCoor);

        mniShowSalaryCoor.setMnemonic('a');
        mniShowSalaryCoor.setText("Ver eventos asignados");
        mniShowSalaryCoor.addActionListener(this::mniShowSalaryCoorActionPerformed);
        mnuCoordinator.add(mniShowSalaryCoor);

        menuEventLogistic.add(mnuCoordinator);

        mnuManager.setMnemonic('e');
        mnuManager.setText("Manager");

        mniManageEvents.setMnemonic('t');
        mniManageEvents.setText("Administrar eventos");
        mniManageEvents.addActionListener(this::mniManageEventsActionPerformed);
        mnuManager.add(mniManageEvents);

        mniManageCoordinators.setMnemonic('y');
        mniManageCoordinators.setText("Administrar Coordinadores");
        mnuManager.add(mniManageCoordinators);

        menuEventLogistic.add(mnuManager);

        mnuOptions.setMnemonic('e');
        mnuOptions.setText("Opciones");

        mniLogOut.setMnemonic('t');
        mniLogOut.setText("Cerrar sesión");
        mnuOptions.add(mniLogOut);

        menuEventLogistic.add(mnuOptions);

        setJMenuBar(menuEventLogistic);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 687, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 495, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mniShowAssignmentsCoorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniShowAssignmentsCoorActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_mniShowAssignmentsCoorActionPerformed

    private void mniShowSalaryCoorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniShowSalaryCoorActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_mniShowSalaryCoorActionPerformed

    private void mniManageEventsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniManageEventsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mniManageEventsActionPerformed

    private void mniShowUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniShowUserActionPerformed
        // TODO add your handling code here: 
        /**if (!(CurrentUser instanceof Logistic)) {
            javax.swing.JOptionPane.showMessageDialog(this, "Esta opción es solo para logísticos");
            return;
        }
       
    
        Logistic logistic = (Logistic) CurrentUser;
        LogisticOpcion frame = new LogisticOpcion(logistic);
        desktopPane.add(frame);
        frame.setVisible(true);
        try {
            frame.setSelected(true);
        } catch (java.beans.PropertyVetoException e) {
            e.printStackTrace();
        }*/
        
    }//GEN-LAST:event_mniShowUserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws Exception {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Main().setVisible(true);
//            }
//        });
        for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
        EventQueue.invokeLater(() -> new LoginFrame2().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuBar menuEventLogistic;
    private javax.swing.JMenuItem mniLogOut;
    private javax.swing.JMenuItem mniManageCoordinators;
    private javax.swing.JMenuItem mniManageEvents;
    private javax.swing.JMenuItem mniManageLogistic;
    private javax.swing.JMenuItem mniShowAssignmentsCoor;
    private javax.swing.JMenuItem mniShowSalaryCoor;
    private javax.swing.JMenuItem mniShowUser;
    private javax.swing.JMenu mnuCoordinator;
    private javax.swing.JMenu mnuLogistic;
    private javax.swing.JMenu mnuManager;
    private javax.swing.JMenu mnuOptions;
    // End of variables declaration//GEN-END:variables

}
