/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.desgroup.ui;

import com.desgroup.models.Logistic;
import javax.swing.*;
import java.awt.*;
/**
 *
 * @author juand
 */
public class LogisticOpcion extends javax.swing.JInternalFrame {
    private Logistic logistic;
    /**
     * Creates new form LogisticOpcion
     */
    public LogisticOpcion(Logistic logistic) {
        super("Opcion Logistico",false,true,false,false);
        this.logistic = logistic;
        setSize(320, 260);
        setLocation(100, 60);
        initializeComponents();
    }
    
    private void initializeComponents(){
        JPanel panel = new JPanel();
        panel.setBorder(BorderFactory.createEmptyBorder(15, 20, 15, 20));
        
        JButton btnEventos = new JButton("Ver eventos");
        JButton btnHoras = new JButton ("Ver Horas");
        JButton btnSueldo = new JButton("Ver sueldo");
        JButton btnUsuario = new JButton("Ver usuario");
        JButton btnVolver = new JButton("Volver");
        
        btnEventos.addActionListener(e -> abrir(new LogisticEventsFrame(logistic)));
        btnSueldo.addActionListener(e -> abrir(new LogisticSalaryFrame(logistic)));
        //btnHoras.addActionListener(e->abrir(new LogisticsHours(Logistic)));
        btnUsuario.addActionListener(e -> abrir(new LogisticUserFrame(logistic)));
        btnVolver.addActionListener(e -> dispose());

        panel.add(btnEventos);
        panel.add(btnSueldo);
        panel.add(btnUsuario);
        panel.add(btnVolver);

        add(panel);
        
        

    }
    
    private void abrir(JInternalFrame f) {
            getDesktopPane().add(f);
            f.setVisible(true);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenu1.setText("file");

        jMenuItem3.setText("Usuario");
        jMenuItem3.addActionListener(this::jMenuItem3ActionPerformed);
        jMenu1.add(jMenuItem3);

        jMenuItem2.setText("Volver");
        jMenuItem2.addActionListener(this::jMenuItem2ActionPerformed);
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 495, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 336, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    // End of variables declaration//GEN-END:variables
}
