/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.desgroup.ui;

import com.desgroup.logic.LogisticService;
import com.desgroup.models.Logistic;
import javax.swing.JPanel;
import javax.swing.*;
import java.awt.*;
/**
 *
 * @author juand
 */
public class LogisticUserFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form LogisticUserFrame
     */
    public LogisticUserFrame(Logistic logistic ) {
        super("Datos del Logístico", true, true, true, true);
        setSize(300, 260);
        setLocation(130, 90);

        JPanel panel = new JPanel(new GridLayout(0, 1, 5, 5));
        panel.setBorder(BorderFactory.createEmptyBorder(15, 15, 15, 15));

        panel.add(new JLabel("Nombre: " + logistic.getName()));
        panel.add(new JLabel("Email: " + logistic.getEmail()));
        panel.add(new JLabel("Teléfono: " + logistic.getPhone()));
        panel.add(new JLabel("Posición: " + logistic.getPosition()));
        panel.add(new JLabel("Zona: " + logistic.getZone()));
        panel.add(new JLabel("Rol: " + logistic.getRole()));
        panel.add(new JLabel("Puntaje: " + logistic.getScore()));

        add(panel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 394, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 274, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
