/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.desgroup.ui;

import com.desgroup.eventlogistics.Main;
import com.desgroup.ui.CreateLogisticFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author urreg
 */
public class ManageLogisticFrame extends javax.swing.JInternalFrame {

    private Main mainFrame; 
    
    /**
     * Creates new form ManageLogisticFrame
     */
    public ManageLogisticFrame(Main mainFrame) {
        super("Administrar logisticos", true, true, true, true);
        this.mainFrame = mainFrame;  
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblManageLogistic = new javax.swing.JTable();
        btnDeleteLogistic = new javax.swing.JButton();
        btnCreateLogistic = new javax.swing.JButton();
        btnUpdatedLogistic = new javax.swing.JButton();

        tblManageLogistic.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Nombre", "Email", "Telefono", "Posición", "Zona", "Rol", "Puntuación"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblManageLogistic);

        btnDeleteLogistic.setText("Eliminar logistico");
        btnDeleteLogistic.addActionListener(this::btnDeleteLogisticActionPerformed);

        btnCreateLogistic.setText("Crear logisitico");
        btnCreateLogistic.addActionListener(this::btnCreateLogisticActionPerformed);

        btnUpdatedLogistic.setText("Actualizar logistico");
        btnUpdatedLogistic.addActionListener(this::btnUpdatedLogisticActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 635, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCreateLogistic, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnUpdatedLogistic, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnDeleteLogistic, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(119, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDeleteLogistic, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdatedLogistic, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCreateLogistic, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteLogisticActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteLogisticActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteLogisticActionPerformed

    private void btnCreateLogisticActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateLogisticActionPerformed
        // TODO add your handling code here:
        btnCreateLogistic.addActionListener(l -> openCreateLogistic());
        
    }//GEN-LAST:event_btnCreateLogisticActionPerformed

    private void btnUpdatedLogisticActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdatedLogisticActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnUpdatedLogisticActionPerformed

    private void openCreateLogistic() {
        CreateLogisticFrame createLogistic = new CreateLogisticFrame();
        mainFrame.add(createLogistic); 
        createLogistic.setVisible(true);
    }
    
    private void openUpdatedLogistic() {
        int fila = tblManageLogistic.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione un producto para editar.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateLogistic;
    private javax.swing.JButton btnDeleteLogistic;
    private javax.swing.JButton btnUpdatedLogistic;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblManageLogistic;
    // End of variables declaration//GEN-END:variables
}
